import os
from enum import Enum
import shutil

import numpy as np
from pandas_datareader._utils import RemoteDataError
from requests.exceptions import RequestException

from lib.Country import Country
from lib.retriever.AlcoholRetriever import AlcoholRetriever
from lib.retriever.AbstractDataRetriever import MAP_STYLE_VERSION, NoComparableDataError
from lib.retriever.ComposedDataRetriever import ComposedDataRetriever
from lib.retriever.CumulativeImmigration import CumulativeImmigration
from lib.retriever.CumulativeInflation import CumulativeInflation
from lib.retriever.EconomicFreedomRetriever import EconomicFreedomRetriever
from lib.retriever.KaggleAverageTemperatureRetriever import KaggleAverageTemperatureRetriever
from lib.retriever.KaggleDebtRetriever import KaggleDebtRetriever
from lib.retriever.KaggleTourismRetriever import KaggleTourismRetriever
from lib.retriever.UnStatRetriever import UnStatRetriever
from lib.retriever.WorldBankDataRetriever import WorldBankDataRetriever, dict_indicators

pyhsicians = WorldBankDataRetriever("SH.MED.PHYS.ZS", alternative_name="Physicians per 1000 people")
gdp_per_capita = WorldBankDataRetriever("NY.GDP.PCAP.CD")
gdp_per_employed = WorldBankDataRetriever("SL.GDP.PCAP.EM.KD", alternative_name="GDP per person employed (PPP $)")
refugee_by_population = ComposedDataRetriever(data_name="Refugees per 1000 people",
                                              retriever_1=WorldBankDataRetriever("SM.POP.RHCR.EA", keep_unit=True),
                                              retriever_2=WorldBankDataRetriever("SP.POP.TOTL"), round=1, is_rate=True,
                                              unit="per 1000 people",
                                              description=dict_indicators["SM.POP.RHCR.EA"].get("sourceNote"),
                                              function=lambda x, y: x / y * 1000 if not np.isnan(x) and not np.isnan(
                                                  y) and y != 0 else np.nan, )
alchool = WorldBankDataRetriever("SH.ALC.PCAP.LI", min_year_range=[2000, 2001], unit="litre of pure alcohol per year")
alchool2 = AlcoholRetriever()
taxRevenue = WorldBankDataRetriever("GC.TAX.TOTL.GD.ZS", keep_unit=True, round=1)
inflation = CumulativeInflation()
debtRetriever = KaggleDebtRetriever()
fossil_fuel = WorldBankDataRetriever("EG.USE.COMM.FO.ZS", keep_unit=True, round=1)
energy_use_per_capita = WorldBankDataRetriever("EG.USE.PCAP.KG.OE")
labor_force = WorldBankDataRetriever("SL.TLF.TOTL.IN")
birth_rate = WorldBankDataRetriever("SP.DYN.CBRT.IN", keep_unit=True)
life_expectancy = WorldBankDataRetriever("SP.DYN.LE00.IN", keep_unit=True)
popover65 = WorldBankDataRetriever("SP.POP.65UP.TO.ZS", keep_unit=True, round=1)
population = WorldBankDataRetriever("SP.POP.TOTL", show_final=False)
north_america_population = WorldBankDataRetriever("SP.POP.TOTL", show_final=True)
north_america_population.output_style_version = f"{MAP_STYLE_VERSION}-na-population-values-v1"
migration = CumulativeImmigration()

# un_intentional_homicies = UnStatRetriever(keep_unit=False, data_name="Intentional Homicide Victims", source="https://data.un.org/DocumentData.aspx?id=497#33", unit="per 100,000 people", description="UNODC Homicide Statistics provide users with a reference for the largest number of countries and the longest time series on homicide data possible. A variety of national and international sources on homicide have been considered to compile UNODC Homicide Statistics and, in order to present accurate and comparable statistics, data have been selected which conform as much as possible to the definition of intentional homicide used by UNODC for statistical purpose: ‘‘unlawful death purposefully inflicted on a person by another person”. All existing data sources on intentional homicides, both at national and international level, stem from either criminal justice or public health systems. In the former case, data are generated by law enforcement or criminal justice authorities in the process of recording and investigating a crime event while, in the latter, data are produced by health authorities certifying the cause of death of an individual. Public health data on homicides were derived from databases on deaths by cause disseminated by WHO, both at central level and through some of its regional offices. Data included in the dataset correspond to the original value provided by the source of origin, since no statistical procedure or modelling was used to change collected values or to create new or revised figures.", show_final=True, series_description="Number of victims of intentional homicide per 100,000 population, by sex (victims per 100,000 population)", category="BOTHSEX", max_year_range=None, round=1, min_year_range=None, indicator="16.1.1")
migration_by_population = ComposedDataRetriever(data_name="Net Migration per 1000 people",
                                                retriever_1=migration,
                                                retriever_2=population, round=0, is_rate=True,
                                                unit="per 1000 people",
                                                description=dict_indicators["SM.POP.NETM"].get("sourceNote"),
                                                function=lambda x, y: x / y * 1000 if not np.isnan(x) and not np.isnan(
                                                    y) and y != 0 else np.nan, )
temperature_retriever = KaggleAverageTemperatureRetriever()
tourism_retriever = KaggleTourismRetriever()
freedom_retriever = EconomicFreedomRetriever()
homicides = WorldBankDataRetriever("VC.IHR.PSRC.P5", min_year_range=[1990, 2002])
militar_expenses = WorldBankDataRetriever("MS.MIL.XPND.GD.ZS", keep_unit=True, round=1)

netNationalIncome = WorldBankDataRetriever("NY.ADJ.NNTY.PC.KD")




class Map(Enum):
    WORLD = {
        "name": "World",
        "retrievers": [
            population,
            gdp_per_capita,
            life_expectancy,
            alchool,
            gdp_per_capita,
        ],
        "crs": "EPSG:4326",
        "legends": {
            "rank": "right",
            "rank_inset": True,
            "description": [(0.035, 0.0), "left", "bottom"],
            "source": [(0.0, 0.0), "left", "bottom"],
            "attribution": [(0.0, 1.0), "left", "top"]
        },
        "map_limits": {
            "minx": -180,
            "maxx": 180,
            "miny": -90,
            "maxy": 90
        },
        "countries": Country.all()
    }
    AMERICAS = {
        "name": "Americas",
        "retrievers": [
            population,
            homicides,
            life_expectancy,
            alchool,
            gdp_per_capita,
            # taxRevenue,
            CumulativeInflation(min_year_range=[2000, 2000]),
            debtRetriever,
            # fossil_fuel,
            # energy_use_per_capita,
            labor_force,
            birth_rate,
            popover65,
            pyhsicians,
            gdp_per_employed,
            refugee_by_population,
            migration,
            migration_by_population,
            temperature_retriever,
            tourism_retriever,
            freedom_retriever,
            militar_expenses,
            netNationalIncome,
            # un_intentional_homicies
        ],
        "crs": "+proj=laea +lat_0=10 +lon_0=-60 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs",
        "legends": {
            "rank": "right",
            "rank_inset": True,
            "description": [(0.035, 0.0), "left", "bottom"],
            "source": [(0.0, 0.0), "left", "bottom"],
            "attribution": [(0.0, 1.0), "left", "top"]
        },
        "map_limits": {
            "minx": -5500000,
            "maxx": 2800000,
            "miny": -6700000,
            "maxy": 8100000
        },
        "countries": [
            # Country.ANTIGUA_BARBUDA,
            # Country.BARBADOS,
            # Country.FRANCE,
            # Country.SAINT_LUCIA,
            Country.ARGENTINA,
            Country.BAHAMAS,
            Country.BELIZE,
            Country.BOLIVIA,
            Country.BRAZIL,
            Country.CANADA,
            Country.CHILE,
            Country.COLOMBIA,
            Country.COSTA_RICA,
            Country.CUBA,
            Country.DOMINICAN_REPUBLIC,
            Country.ECUADOR,
            Country.EL_SALVADOR,
            Country.FRENCH_GUYANA,
            Country.GUATEMALA,
            Country.GUYANA,
            Country.HAITI,
            Country.HONDURAS,
            Country.JAMAICA,
            Country.MEXICO,
            Country.NICARAGUA,
            Country.PANAMA,
            Country.PARAGUAY,
            Country.PERU,
            Country.PUERTO_RICO,
            Country.SURINAME,
            Country.TRINIDAD_TOBAGO,
            Country.UNITED_STATES,
            Country.URUGUAY,
            Country.VENEZUELA,
        ]
    }
    NORTH_AMERICA = {
        "name": "North America",
        "style_revision": "small-southern-labels-v2",
        "small_label_countries": [
            Country.BAHAMAS,
            Country.BELIZE,
            Country.CUBA,
            Country.DOMINICAN_REPUBLIC,
            Country.GUATEMALA,
            Country.HAITI,
            Country.HONDURAS,
            Country.EL_SALVADOR,
            Country.JAMAICA,
            Country.NICARAGUA,
            Country.COSTA_RICA,
            Country.PANAMA,
        ],
        "small_label_font_reduction": 3,
        "retrievers": [
            north_america_population,
            homicides,
            life_expectancy,
            alchool,
            gdp_per_capita,
            CumulativeInflation(min_year_range=[2000, 2000]),
            debtRetriever,
            labor_force,
            birth_rate,
            popover65,
            pyhsicians,
            gdp_per_employed,
            refugee_by_population,
            migration,
            migration_by_population,
            temperature_retriever,
            tourism_retriever,
            freedom_retriever,
            militar_expenses,
            netNationalIncome,
        ],
        "crs": "+proj=laea +lat_0=10 +lon_0=-60 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs",
        "legends": {
            "rank": "right",
            "rank_inset": True,
            "description": [(0.01, 0.94), "left", "top"],
            "description_follows_rank": False,
            "source": [(0.0, 0.0), "left", "bottom"],
            "attribution": [(0.995, 0.01), "right", "bottom"]
        },
        "map_limits": {
            "minx": -9000000,
            "maxx": 2800000,
            "miny": -600000,
            "maxy": 8900000
        },
        "countries": [
            Country.BAHAMAS,
            Country.BELIZE,
            Country.CANADA,
            Country.COSTA_RICA,
            Country.CUBA,
            Country.DOMINICAN_REPUBLIC,
            Country.EL_SALVADOR,
            Country.GUATEMALA,
            Country.HAITI,
            Country.HONDURAS,
            Country.JAMAICA,
            Country.MEXICO,
            Country.NICARAGUA,
            Country.PANAMA,
            Country.UNITED_STATES,
        ]
    }
    ASIA = {
        "retrievers": [
            population,
            gdp_per_capita,
            life_expectancy,
            # fossil_fuel,
            energy_use_per_capita,
            militar_expenses,
            migration_by_population,
            debtRetriever,
            freedom_retriever,
            alchool,
            labor_force,
            gdp_per_employed,
            pyhsicians,
            birth_rate,
            popover65,
            homicides,
            temperature_retriever,
            tourism_retriever,
            refugee_by_population,
            # un_intentional_homicies
        ],
        "name": "Asia",
        "crs": "+proj=lcc +lat_1=15 +lat_2=45 +lat_0=30 +lon_0=100 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs",
        "legends": {
            "rank": "left",
            "description": [(0.035, 0.0), "left", "bottom"],
            "source": [(1.0, 0.0), "right", "bottom"],
            "attribution": [(1.0, 1.0), "right", "top"]
        },

        "map_limits": {
            "minx": -6000000,
            "maxx": 4000000,
            "miny": -4500000,
            "maxy": 3500000
        },
        "countries": [
            Country.AFGHANISTAN,
            Country.BAHRAIN,
            Country.BANGLADESH,
            Country.BHUTAN,
            Country.BRUNEI,
            Country.AZERBAIJAN,
            Country.GEORGIA,
            Country.ARMENIA,
            Country.CAMBODIA,
            Country.EAST_TIMOR,
            Country.INDIA,
            Country.INDONESIA,
            Country.IRAN,
            Country.IRAQ,
            Country.ISRAEL,
            Country.JAPAN,
            Country.JORDAN,
            Country.KUWAIT,
            Country.KAZAKHSTAN,
            Country.KYRGYZSTAN,
            Country.LAOS,
            Country.LEBANON,
            Country.MALAYSIA,
            Country.MALDIVES,
            Country.MONGOLIA,
            Country.MYANMAR,
            Country.NEPAL,
            Country.NORTH_KOREA,
            Country.OMAN,
            Country.PAKISTAN,
            Country.PALESTINE,
            Country.PHILIPPINES,
            Country.QATAR,
            Country.SAUDI_ARABIA,
            Country.SINGAPORE,
            Country.SOUTH_KOREA,
            Country.SRI_LANKA,
            Country.SYRIA,
            Country.TAJIKISTAN,
            Country.THAILAND,
            Country.TURKEY,
            Country.TURKMENISTAN,
            Country.UNITED_ARAB_EMIRATES,
            Country.UZBEKISTAN,
            Country.VIETNAM,
            Country.YEMEN,
            Country.CHINA,
            Country.TAIWAN,
            Country.RUSSIA,
        ]}

    OCEANIA = {
        "name": "Oceania",
        "retrievers": [
            population,
            gdp_per_capita,
            life_expectancy,
            alchool,
            labor_force,
            gdp_per_employed,
            pyhsicians,
            birth_rate,
            migration_by_population,
            # un_intentional_homicies
        ],
        "crs": "+proj=eqearth +lon_0=160 +datum=WGS84 +units=m +no_defs",
        "legends": {
            "rank": "left",
            "rank_inset": True,
            "description": [(0.035, 0.0), "left", "bottom"],
            "source": [(1.0, 0.0), "right", "bottom"],
            "attribution": [(1.0, 1.0), "right", "top"]
        },
        "map_limits": {
            "minx": -4400000,
            "maxx": 3200000,
            "miny": -5800000,
            "maxy": 480000
        },
        "countries": [
            Country.AUSTRALIA,
            Country.NEW_ZEALAND,
            Country.FIJI,
            Country.PAPUA_NEW_GUINEA,
            Country.SOLOMON_ISLANDS,
            Country.VANUATU,
            Country.SAMOA,
            Country.TONGA,
            Country.MICRONESIA,
            Country.KIRIBATI,
            Country.INDONESIA,
            Country.NEW_CALEDONIA,
            Country.FRENCH_POLYNESIA,
            Country.GUAM,
            Country.NAURU,
            Country.PALAU,
            Country.MARSHALL_ISLANDS,
            Country.TUVALU,
            Country.AMERICAN_SAMOA,
            Country.NORTHERN_MARIANA_ISLANDS,
        ]
    }

    AFRICA = {
        "name": "Africa",
        "retrievers": [
            population,
            migration_by_population
        ],
        "crs": "+proj=laea +lat_0=7 +lon_0=20 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs",
        "legends": {
            "rank": "right",
            "rank_inset": True,
            "description": [(1, 0.0), "right", "bottom"],
            "source": [(0, 0.0), "left", "bottom"],
            "attribution": [(0, 1.0), "left", "top"]
        },
        "map_limits": {
            "minx": -3.99e6,
            "maxx": 4.08e6,
            "miny": -4.82e6,
            "maxy": 3.5e6
        },
        "countries": [
            Country.ALGERIA,
            Country.ANGOLA,
            Country.BENIN,
            Country.BOTSWANA,
            Country.BURKINA_FASO,
            Country.BURUNDI,
            Country.CABO_VERDE,
            Country.CAMEROON,
            Country.CENTRAL_AFRICAN_REPUBLIC,
            Country.CHAD,
            Country.COMOROS,
            Country.CONGO,
            Country.COTE_DIVOIRE,
            Country.DEMOCRATIC_REPUBLIC_OF_THE_CONGO,
            Country.DJIBOUTI,
            Country.EGYPT,
            Country.EQUATORIAL_GUINEA,
            Country.ERITREA,
            Country.ETHIOPIA,
            Country.ESWATINI,
            Country.GABON,
            Country.GAMBIA,
            Country.GHANA,
            Country.GUINEA,
            Country.GUINEA_BISSAU,
            Country.KENYA,
            Country.LESOTHO,

            Country.LIBERIA,
            Country.LIBYA,
            Country.MADAGASCAR,
            Country.MALAWI,
            Country.MALI,
            Country.MAURITANIA,
            Country.MAURITIUS,
            Country.MOROCCO,
            Country.MOZAMBIQUE,
            Country.NAMIBIA,
            Country.NIGER,
            Country.NIGERIA,
            Country.RWANDA,
            Country.SAO_TOME_PRINCIPE,
            Country.SENEGAL,
            Country.SEYCHELLES,
            Country.SIERRA_LEONE,
            Country.SOMALIA,
            Country.SOUTH_AFRICA,
            Country.SOUTH_SUDAN,
            Country.SUDAN,
            Country.TANZANIA,
            Country.TOGO,
            Country.TUNISIA,
            Country.UGANDA,
            Country.WESTERN_SAHARA,
            Country.ZAMBIA,
            Country.ZIMBABWE,
            Country.REUNION,
            Country.MAYOTTE
        ]
    }

    EUROPE = {
        "name": "Europe",
        "retrievers": [
            alchool2,
            inflation,
            debtRetriever,
            fossil_fuel,
            energy_use_per_capita,
            taxRevenue,
            militar_expenses,
            netNationalIncome,
            gdp_per_capita,
            alchool,
            migration,
            migration_by_population,
            pyhsicians,
            # arms,
            gdp_per_employed,
            labor_force,
            WorldBankDataRetriever("SM.POP.RHCR.EA", keep_unit=True),
            birth_rate,
            life_expectancy,
            popover65,
            WorldBankDataRetriever("SP.POP.TOTL", show_final=True),
            WorldBankDataRetriever("VC.IHR.PSRC.P5"),
            temperature_retriever,
            tourism_retriever,
            freedom_retriever,
            refugee_by_population,
            # un_intentional_homicies
        ],
        "crs": "3035",
        "legends": {
            "rank": "right",
            "description": [(1, 0.01), "right", "bottom"],
            "source": [(0.01, 0.01), "left", "bottom"],
            "attribution": [(0.995, 0.994), "right", "top"]
        },
        "map_limits": {
            "minx": 2620000,
            "maxx": 7600000,
            "miny": 1390000,
            "maxy": 5430000
        },
        "countries": [
            Country.ALBANIA,
            Country.ANDORRA,
            Country.AZERBAIJAN,
            Country.ARMENIA,
            Country.AUSTRIA,
            Country.BELGIUM,
            Country.BELARUS,
            Country.BOSNIA_HERZEGOVINA,
            Country.BULGARIA,
            Country.CYPRUS,
            Country.CZECHIA,
            Country.CROATIA,
            Country.DENMARK,
            Country.ESTONIA,
            Country.FINLAND,
            Country.FRANCE,
            Country.GEORGIA,
            Country.GERMANY,
            Country.GREECE,
            Country.HUNGARY,
            Country.KAZAKHSTAN,
            Country.KOSOVO,
            Country.ICELAND,
            Country.IRELAND,
            Country.ITALY,
            Country.LATVIA,
            Country.LIECHTENSTEIN,
            Country.LITHUANIA,
            Country.LUXEMBOURG,
            Country.MOLDOVA,
            Country.NORTH_MACEDONIA,
            Country.MALTA,
            Country.MONACO,
            Country.MONTENEGRO,
            Country.NETHERLANDS,
            Country.NORWAY,
            Country.POLAND,
            Country.PORTUGAL,
            Country.ROMANIA,
            Country.RUSSIA,
            Country.SAN_MARINO,
            Country.SERBIA,
            Country.SLOVAKIA,
            Country.SLOVENIA,
            Country.SPAIN,
            Country.SWEDEN,
            Country.SWITZERLAND,
            Country.TURKEY,
            Country.UKRAINE,
            Country.UNITED_KINGDOM
        ]
    }

    def __getitem__(self, item):
        return item

    @property
    def name(self):
        return self.value["name"]

    @property
    def map_limits(self):
        return self.value["map_limits"]

    @property
    def countries(self) -> list[Country]:
        return self.value["countries"]

    @property
    def iso3_list(self):
        return [country.iso3 for country in self.countries]

    @property
    def iso2_list(self):
        return [country.iso2 for country in self.countries]

    @property
    def crs(self):
        return self.value["crs"]

    @property
    def description_position(self):
        return self.value["legends"]["description"]

    @property
    def description_follows_rank(self):
        return self.value["legends"].get("description_follows_rank", True)

    @property
    def source_position(self):
        return self.value["legends"]["source"]

    @property
    def attribution_position(self):
        return self.value["legends"]["attribution"]

    @property
    def style_revision(self):
        return self.value.get("style_revision")

    def label_font_reduction(self, country):
        if country in self.value.get("small_label_countries", []):
            return self.value.get("small_label_font_reduction", 0)
        return 0

    @property
    def retrievers(self):
        return self.value["retrievers"]

    @property
    def rank_position(self):
        return self.value["legends"]["rank"]

    @property
    def rank_inset(self):
        return self.value["legends"].get("rank_inset", False)

    def to_reddit(self):
        reddit_folder = f"data/reddit/{self.name}"
        error_log_path = f"{reddit_folder}/errors.log"
        os.makedirs(reddit_folder, exist_ok=True)
        for i, ret in enumerate(self.retrievers):
            try:
                filename = ret.plot(region=self)
            except NoComparableDataError as error:
                indicator = getattr(ret, "indicator", ret.data_name)
                message = f"Skipping {ret.data_name} ({indicator}) for {self.name}: {error}"
                with open(error_log_path, "a", encoding="utf-8") as error_log:
                    print(message, file=error_log)
                continue
            except (RequestException, RemoteDataError) as error:
                indicator = getattr(ret, "indicator", ret.data_name)
                message = (
                    f"Skipping {ret.data_name} ({indicator}) for {self.name} "
                    f"after download retries were exhausted: {error}"
                )
                with open(error_log_path, "a", encoding="utf-8") as error_log:
                    print(message, file=error_log)
                continue
            padded_i = str(i + 1).zfill(2)
            shutil.copy(filename, f"{reddit_folder}/{padded_i}.{ret.data_name}.png")
